import os
import logging
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple, Any
import bio_pockets
from bio_pockets.config_manager import load_config


"""
Consensus Analyzer Module

Compares pocket detection results across multiple detection presets and 
generates a unified consensus ranking based on agreement/disagreement patterns.

Core Concept:
    Instead of running ONE detection method, run THREE independently optimized
    methods (small_enzymes, medium_proteins, large_proteins) and identify pockets
    that are consistent across multiple methods. This cross-validation approach:
    
    • Reduces false positives (artifacts appear in only 1 method)
    • Identifies robust binding sites (appear in all/most methods)
    • Provides confidence metrics (robustness scores)
    • Improves generalization across protein sizes

Typical Workflow:
    1. Run analysis with small_enzymes preset → ranking1 (100+ pockets)
    2. Run analysis with large_proteins preset → ranking2 (80+ pockets)
    3. Run analysis with medium_proteins preset → ranking3 (90+ pockets)
    4. Match pockets spatially across presets
    5. Calculate robustness scores (0-1: fraction of presets detecting it)
    6. Generate consensus ranking weighted by robustness + average score
    7. Output: consensus list with confidence metrics
    8. Save reports: human-readable text + CSV for spreadsheet analysis

Key Concepts:
    • Spatial Matching: Two pockets are "the same" if centers <5.0 Å apart
    • Robustness: Fraction of presets that detected a pocket (0/3, 1/3, 2/3, 3/3)
    • Consensus Score: Weighted combination of average_score + robustness
    
Typical Output:
    Rank 1: Pocket detected by all 3 presets (robustness=1.00), high score → VERY CONFIDENT
    Rank 2: Pocket detected by 2 presets (robustness=0.67), medium score → MODERATELY CONFIDENT
    Rank 3: Pocket detected by 1 preset (robustness=0.33), high score → LOW CONFIDENCE

Dependencies:
    • NumPy: Numerical computations and array operations
    • pandas: Dataframe operations for CSV export
    • logging: Diagnostic output during analysis
    • bio_pockets: Pocket detection pipeline
"""

logger = logging.getLogger(__name__)


class ConsensusAnalyzer:
    """
    Orchestrates multi-preset pocket detection and generates robustness-weighted consensus ranking.
    
    This class manages the comparison of pocket detection results from different presets
    (parameter sets), identifies which pockets are consistently detected across methods,
    and produces a final consensus ranking with confidence metrics.
    
    Algorithm Overview:
        1. Store ranking results from each preset independently
        2. Use first preset as reference
        3. For each pocket in reference:
           - Find spatially matching pockets in other presets
           - Record scores from all matching presets
        4. Calculate robustness = (# presets detecting it) / (total # presets)
        5. Calculate consensus_score = 70% * average_score + 30% * robustness
        6. Sort by consensus_score
    
    Attributes:
        results_by_preset (dict): Maps preset_name → list of ranked pocket dicts
                                 Each pocket dict contains: id, score, size, preference, residues, etc.
        consensus_ranking (list): Final consensus ranking with robustness/average scores
    
    """
    
    def __init__(self):
        # Dictionary storing results from each preset analysis
        # Key: preset name (e.g., 'small_enzymes')
        # Value: list of dicts with pocket rankings
        self.results_by_preset = {}
        
        # Final consensus ranking generated by generate_consensus()
        # Will be None until generate_consensus() is called
        self.consensus_ranking = None
    
    def add_result(self, preset_name: str, ranked_pockets: List[Dict[str, Any]]):
        """
        Register pocket detection results from a single preset analysis.
        
        This function stores the output from one independent preset run.
        Call this once for each preset you want to analyze.
        
        Args:
            preset_name (str): Name identifying the preset configuration.
                              Examples: 'small_enzymes', 'medium_proteins', 'large_proteins'
                              Used as key in internal storage and in final reports.
            
            ranked_pockets (list): Ranking output from rank_pockets_master_score()
                                  Each element is a dict with keys:
                                  - 'id': Pocket identifier (int)
                                  - 'score': Ranking score (0-100 scale)
                                  - 'size': Number of grid points in pocket (int)
                                  - 'preference': Chemical character (str: "lipophilic", "polar", etc.)
                                  - 'residues': List of nearby residue IDs (list of str)
        
        """
        self.results_by_preset[preset_name] = ranked_pockets
        logger.info(f"Added results from preset '{preset_name}': {len(ranked_pockets)} pockets")
    
    def _match_pockets(self, pocket1: np.ndarray, pocket2: np.ndarray, 
                       threshold: float = 5.0) -> bool:
        """
        Determine if two pockets represent the same spatial location.
        
        Strategy: Compare centers of mass (centroids) of the two 3D point clouds.
        If centroids are within threshold distance → they are the same pocket detected
        by two different presets.
        
        Why use centroid distance?
            • Fast: O(1) computation
            • Robust: Averaging reduces noise from individual points
            • Intuitive: Center-to-center distance reflects pocket location
            • Empirically validated: 5.0 Å threshold distinguishes:
              - Same pocket detected twice: typically 1-3 Å apart
              - Different neighboring pockets: typically 8-15 Å apart
        
        Alternative approaches NOT used:
            • Hausdorff distance: Too strict, penalizes different point clouds
            • Intersection over union: Requires resampling to same grid
            • Chamfer distance: Computationally expensive
        
        Args:
            pocket1 (np.ndarray): Array of shape (N, 3) containing 3D coordinates of pocket points
                                 from first preset. N can vary (depends on grid spacing, pocket size).
            pocket2 (np.ndarray): Array of shape (M, 3) containing 3D coordinates of pocket points
                                 from second preset. M can differ from N.
            threshold (float, optional): Maximum center-to-center distance in Ångströms
                                       to consider pockets as the same.
                                       Default: 5.0 Å
                                       - Smaller (3.0 Å): Very strict, may split same pocket
                                       - Typical (5.0 Å): Recommended for most cases
                                       - Larger (7.0 Å): Loose, may merge different pockets
        
        Returns:
            bool: True if pockets are spatially similar (same binding site).
                 False if they are different locations.
        
        """
        # Calculate center of mass for each point cloud
        # mean(axis=0) averages across all N/M points to get single (x, y, z) point
        center1 = pocket1.mean(axis=0)
        center2 = pocket2.mean(axis=0)
        
        # Euclidean distance: sqrt((x1-x2)^2 + (y1-y2)^2 + (z1-z2)^2)
        distance = np.linalg.norm(center1 - center2)
        
        return distance < threshold
    
    def generate_consensus(self, pocket_coords_dict: Dict[str, Dict[int, np.ndarray]],
                          spatial_threshold: float = 5.0) -> List[Dict[str, Any]]:
        """
        Generate consensus ranking across all presets with robustness scoring.
        
        This is the core algorithm that:
        1. Identifies which pockets are consistently detected across presets
        2. Averages scores for matched pockets
        3. Calculates robustness (confidence) metrics
        4. Produces final ranked list weighted by consistency
        
        Detailed Algorithm:
        
        Phase 1: Initialize
            • Select first preset as reference (arbitrary choice)
            • Prepare to track which pockets have been matched
        
        Phase 2: For each pocket in reference preset
            • Get its coordinates and score
            • Skip if already matched to another pocket
            • Initialize matches dict with reference score
        
        Phase 3: Search for matches in other presets
            For each OTHER preset:
                For each pocket in that preset:
                    • Check if centroids are within spatial_threshold (5.0 Å)
                    • If yes: record score and pocket ID
                    • Keep only BEST match (closest distance)
        
        Phase 4: Calculate consensus metrics
            robustness = (# presets detecting it) / (total # presets)
                Example: 3 presets total, detected in 2 → robustness = 0.67
            
            average_score = mean of scores from all presets that detected it
                Example: small=24.5, large=25.1 (medium didn't detect)
                        → average = (24.5 + 25.1) / 2 = 24.8
            
            score_std = standard deviation of scores
                Indicates consensus quality:
                • std=0.2: All presets agree strongly
                • std=2.0: Presets disagree on strength
            
            consensus_score = 0.7 * average_score + 0.3 * (robustness * 100)
                Weighting: 70% is geometry/binding strength, 30% is consistency
                Example: avg=24.5, robustness=0.67
                        → score = 0.7*24.5 + 0.3*67 = 17.15 + 20.1 = 37.25
        
        Args:
            pocket_coords_dict (dict): Nested dict mapping coordinates to pockets.
                                      Structure: {preset_name: {pocket_id: coordinate_array}}
                                      Example:
                                      {
                                        'small_enzymes': {
                                            1: np.array([[10, 20, 30], [10.5, 20.2, 30.1], ...]),
                                            2: np.array([[40, 50, 60], ...]),
                                            ...
                                        },
                                        'large_proteins': {
                                            1: np.array([[10.1, 20.1, 30.1], ...]),
                                            ...
                                        },
                                        ...
                                      }
            
            spatial_threshold (float): Maximum distance (Ångströms) between pocket centers
                                      to consider them matching pockets.
                                      Configuration parameter:
                                      • 3.0 Å: Very strict (only nearly identical pockets match)
                                      • 5.0 Å: Standard (RECOMMENDED)
                                      • 7.0 Å: Loose (may over-merge different pockets)
        
        Returns:
            list: Consensus ranking sorted by consensus_score (highest first).
                 Each element is a dict containing:
                 - 'reference_id': Pocket ID from reference preset
                 - 'consensus_score': Final score 0-100 (higher = better)
                 - 'average_score': Mean score across detecting presets
                 - 'score_std': Standard deviation (consistency metric)
                 - 'robustness': Fraction 0-1 (0=detected by 1 preset, 1=all presets)
                 - 'num_presets': Count of presets detecting it (e.g., 2 out of 3)
                 - 'preset_scores': Dict {preset_name: score}
                 - 'size': Number of grid points
                 - 'preference': Chemical character ("lipophilic", "polar", etc.)
                 - 'residues': List of nearby residue identifiers
        
        Raises:
            ValueError: If no results have been added via add_result()

        """
        if not self.results_by_preset:
            raise ValueError("No results added. Call add_result() first.")
        
        logger.info("Generating consensus ranking...")
        
        consensus_pockets = []
        # Track which pocket IDs have been matched to avoid counting same pocket twice
        matched_sets = set()
        
        #  Use first preset as reference (arbitrary starting point) 
        reference_preset = list(self.results_by_preset.keys())[0]
        reference_results = self.results_by_preset[reference_preset]
        reference_coords = pocket_coords_dict.get(reference_preset, {})
        
        #  Iterate through reference preset pockets 
        for ref_pocket in reference_results:
            pocket_id = ref_pocket['id']
            ref_score = ref_pocket['score']
            
            # Skip if already matched to another pocket (avoid duplicates)
            if pocket_id in matched_sets:
                continue
            
            # Initialize matches with reference preset's score
            matches = {reference_preset: ref_score}
            matched_coords_dict = {reference_preset: reference_coords.get(pocket_id)}
            
            #  Search for matching pockets in other presets 
            for other_preset in self.results_by_preset:
                if other_preset == reference_preset:
                    continue
                
                other_results = self.results_by_preset[other_preset]
                other_coords_dict = pocket_coords_dict.get(other_preset, {})
                
                # Get reference pocket coordinates for spatial comparison
                ref_coords = reference_coords.get(pocket_id)
                if ref_coords is None:
                    continue
                
                # Find BEST matching pocket in this other preset
                # (closest to reference, within spatial threshold)
                best_match_score = None
                best_match_id = None
                best_match_distance = float('inf')
                
                for other_pocket in other_results:
                    other_id = other_pocket['id']
                    other_coords = other_coords_dict.get(other_id)
                    
                    if other_coords_dict is None:
                        continue
                    
                    # Check spatial overlap using centroid distance
                    if self._match_pockets(ref_coords, other_coords, spatial_threshold):
                        # Calculate distance for ranking (keep closest match)
                        center_dist = np.linalg.norm(
                            ref_coords.mean(axis=0) - other_coords.mean(axis=0)
                        )
                        
                        # Update best match if this is closer
                        if center_dist < best_match_distance:
                            best_match_distance = center_dist
                            best_match_score = other_pocket['score']
                            best_match_id = other_pocket['id']
                
                # If we found a match in this preset, record it
                if best_match_score is not None:
                    matches[other_preset] = best_match_score
                    matched_coords_dict[other_preset] = other_coords_dict.get(best_match_id)
                    if best_match_id is not None:
                        matched_sets.add(best_match_id)
            
            #  Calculate consensus metrics 
            # Robustness: fraction of presets detecting this pocket
            # Example: 2 out of 3 presets → robustness = 2/3 = 0.667
            num_presets_detected = len(matches)
            
            # Average score across all presets that detected this pocket
            average_score = np.mean(list(matches.values()))
            
            # Standard deviation: how consistent are the scores?
            # High std (>2): Presets disagree on ranking
            # Low std (<0.5): Presets strongly agree
            score_std = np.std(list(matches.values())) if len(matches) > 1 else 0
            
            # Robustness on 0-1 scale (fraction of presets)
            robustness = num_presets_detected / len(self.results_by_preset)
            
            # Final consensus score: weighted combination
            # 70% weight on average score (quality of binding site)
            # 30% weight on robustness (confidence in prediction)
            # Robustness is multiplied by 100 to put on similar scale to average_score
            consensus_score = (average_score * 0.7) + (robustness * 100 * 0.3)
            
            # Create consensus pocket entry
            consensus_pockets.append({
                'reference_id': pocket_id,
                'consensus_score': round(consensus_score, 1),
                'average_score': round(average_score, 1),
                'score_std': round(score_std, 1),
                'robustness': round(robustness, 2),  # Fraction: 0.33, 0.67, 1.00
                'num_presets': num_presets_detected,
                'preset_scores': {k: round(v, 1) for k, v in matches.items()},
                'size': ref_pocket['size'],
                'preference': ref_pocket['preference'],
                'residues': ref_pocket['residues']
            })
            
            matched_sets.add(pocket_id)
        
        # Sort by consensus score (highest first = best consensus binding sites)
        consensus_pockets.sort(key=lambda x: x['consensus_score'], reverse=True)
        self.consensus_ranking = consensus_pockets
        
        logger.info(f"Generated consensus ranking for {len(consensus_pockets)} pockets")
        return consensus_pockets
    
    def save_consensus_report(self, filename: str = "consensus_ranking.txt"):
        """
        Export consensus ranking to human-readable text report.
        
        Format: One pocket per block with detailed metrics.
        
        Output Format:
        ```
        RANK 1 | POCKET 1 | CONSENSUS SCORE: 85.3 | ROBUSTNESS: 1.00 (3/3 presets)
        Average Score: 24.5 ± 0.3 | Size: 250 points | Preference: Lipophilic
        Preset Scores: small_enzymes=24.2, large_proteins=24.7, medium_proteins=24.6
        Residues: ALA183, ARG173, SER45, ... (10 shown, more available)
        ```
        
        Args:
            filename (str, optional): Output file path.
                                    Default: "consensus_ranking.txt"
        
        Raises:
            RuntimeError: If generate_consensus() has not been called yet
        
         """
        if not self.consensus_ranking:
            logger.warning("No consensus ranking generated yet")
            return
        
        with open(filename, 'w') as f:
            f.write("POCKET FINDER: CONSENSUS RANKING ACROSS ALL PRESETS\n")
            f.write("="*80 + "\n")
            f.write(f"Total presets analyzed: {len(self.results_by_preset)}\n")
            f.write(f"Presets: {', '.join(self.results_by_preset.keys())}\n")
            f.write("="*80 + "\n\n")
            
            for i, pocket in enumerate(self.consensus_ranking):
                f.write(f"RANK {i+1} | POCKET {pocket['reference_id']} | ")
                f.write(f"CONSENSUS SCORE: {pocket['consensus_score']}\n")
                
                # Robustness as percentage and fraction
                f.write(f"Robustness: {pocket['robustness']*100:.0f}% ")
                f.write(f"({pocket['num_presets']}/{len(self.results_by_preset)} presets)\n")
                
                # Average score with variation indicator
                f.write(f"Average Score: {pocket['average_score']} ")
                if pocket['score_std'] > 0:
                    f.write(f"± {pocket['score_std']}\n")
                else:
                    f.write(f"(no variation)\n")
                
                f.write(f"Size: {pocket['size']} points | ")
                f.write(f"Preference: {pocket['preference']}\n")
                
                # Individual preset scores for transparency
                f.write(f"Preset Scores: ")
                score_strs = [f"{p}={s}" for p, s in pocket['preset_scores'].items()]
                f.write(", ".join(score_strs) + "\n")
                
                # Associated residues (first 10 shown, rest summarized)
                f.write(f"Residues: {', '.join(pocket['residues'][:10])}")
                if len(pocket['residues']) > 10:
                    f.write(f" ... and {len(pocket['residues'])-10} more")
                f.write("\n\n")
        
        logger.info(f"Consensus report saved to: {filename}")
    
    def save_comparison_table(self, filename: str = "preset_comparison.csv"):
        """
        Export consensus ranking as CSV spreadsheet for quantitative analysis.
        
        CSV Format: One row per pocket, easy to import to Excel/R/Python pandas.
        
        Columns:
            • pocket_id: Pocket identifier from reference preset
            • consensus_score: Final score (0-100, higher = better)
            • robustness: Fraction 0-1 (detection consistency across presets)
            • num_presets_detected: Count of presets detecting it (1, 2, 3, etc.)
            • average_score: Mean score across presets
            • std_score: Standard deviation (measure of agreement)
            • size_points: Number of grid points in pocket
            • preference: Chemical character (lipophilic, polar, mixed, etc.)
            • score_small_enzymes: Score from small_enzymes preset (if ran)
            • score_large_proteins: Score from large_proteins preset (if ran)
            • score_medium_proteins: Score from medium_proteins preset (if ran)
            (Additional columns for any other presets)
        
        Args:
            filename (str, optional): Output CSV file path.
                                    Default: "preset_comparison.csv"
        
        Returns:
            pd.DataFrame: The exported dataframe (for further analysis in Python)
        
         """
        if not self.consensus_ranking:
            logger.warning("No consensus ranking generated yet")
            return
        
        # Build data structure for DataFrame conversion
        data = []
        
        for pocket in self.consensus_ranking:
            row = {
                'pocket_id': pocket['reference_id'],
                'consensus_score': pocket['consensus_score'],
                'robustness': pocket['robustness'],
                'num_presets_detected': pocket['num_presets'],
                'average_score': pocket['average_score'],
                'std_score': pocket['score_std'],
                'size_points': pocket['size'],
                'preference': pocket['preference']
            }
            
            # Add individual preset scores as separate columns
            # This allows filtering/sorting by specific preset scores
            for preset, score in pocket['preset_scores'].items():
                row[f'score_{preset}'] = score
            
            data.append(row)
        
        # Create DataFrame and export to CSV
        df = pd.DataFrame(data)
        df.to_csv(filename, index=False)
        logger.info(f"Comparison table saved to: {filename}")
        
        return df
    
    def print_summary(self):
        """
        Print summary statistics of consensus analysis to console.
        
        Output includes:
        - Number of presets analyzed
        - Total pockets in consensus
        - Distribution by robustness level
        - Top 5 consensus scores
        - Top 3 pockets by score
        
        Useful for quick overview of results during interactive analysis.
        
        """
        if not self.consensus_ranking:
            print("No consensus ranking generated yet")
            return
        
        print("\n" + "="*80)
        print("CONSENSUS ANALYSIS SUMMARY")
        print("="*80)
        print(f"Presets analyzed: {len(self.results_by_preset)}")
        print(f"  - {', '.join(self.results_by_preset.keys())}")
        print(f"\nTotal pockets in consensus: {len(self.consensus_ranking)}")
        
        # Count pockets by robustness level
        robustness_100 = sum(1 for p in self.consensus_ranking if p['robustness'] == 1.0)
        robustness_high = sum(1 for p in self.consensus_ranking if p['robustness'] >= 0.67)
        
        print(f"\nRobustness Distribution:")
        print(f"  - Detected in ALL presets (100%): {robustness_100}")
        print(f"  - Detected in 2+ presets (≥67%): {robustness_high}")
        print(f"  - Detected in only 1 preset: {len(self.consensus_ranking) - robustness_high}")
        
        # Top 5 scores for quick reference
        top5_scores = [p['consensus_score'] for p in self.consensus_ranking[:5]]
        print(f"\nTop 5 Consensus Scores: {top5_scores}")
        
        print("\nTop 3 Pockets (by Consensus Score):")
        for i, pocket in enumerate(self.consensus_ranking[:3]):
            print(f"  {i+1}. Pocket {pocket['reference_id']}: "
                  f"Score={pocket['consensus_score']} "
                  f"(Robustness={pocket['robustness']*100:.0f}%, "
                  f"StdDev=±{pocket['score_std']})")
        
       


def analyze_all_presets(protein_pdb: str, base_config: str, 
                        presets: List[str],
                        output_prefix: str = None) -> Tuple[List[Dict], pd.DataFrame]:
    """
    High-level orchestration function: Run all presets and generate unified consensus.
    
    This is the main entry point for complete multi-preset analysis. It handles the
    entire workflow: running each preset, managing temporary files, merging results,
    and saving outputs.
    
    Complete Workflow:
        1. For each preset in the list:
           - Load preset-specific config
           - Clean structure
           - Extract sequence
           - Generate conservation scores (if enabled)
           - Run pocket detection
           - Rank pockets
           - Store results
           - Clean up temporary files
        2. Generate consensus across all presets
        3. Generate and save reports
        4. Return results for further analysis
    
    Configuration Parameters (loaded from YAML):
        All parameters are loaded from preset-specific config files:
        
        grid:
            spacing_angstrom (float): Grid point spacing (0.5-2.0 Å)
        
        geometry:
            min_distance_angstrom (float): Minimum distance from protein
            max_distance_angstrom (float): Maximum distance from protein
            surface_threshold_angstrom (float): Neighborhood radius
            min/max_neighbors (int): Atom count thresholds
            enclosure_check: Evaluate if pockets are protein-enclosed
        
        clustering:
            eps_angstrom (float): DBSCAN epsilon
            min_samples (int): DBSCAN minimum cluster size
            min/max_points (int): Size filters for final pockets
        
        conservation:
            enabled (bool): Run alignment and conservation scoring
            jackhmmer_cpus (int): CPU threads for alignment
            default_database (str): Path to sequence database
        
        master_score:
            weight_volume (float): Importance of pocket size
            weight_hydrophobicity (float): Importance of hydrophobic character
            weight_conservation (float): Importance of evolutionary conservation
    
    Args:
        protein_pdb (str): Path to input PDB file (e.g., "/data/1abc.pdb")
        base_config (str): Path to base configuration file (e.g., "config.yaml")
        presets (list): List of preset names to run.
                       Examples: ['small_enzymes', 'large_proteins', 'medium_proteins']
                       Order doesn't matter (first is used as reference in consensus).
        output_prefix (str, optional): Prefix for output files.
                                      Default: protein name (from filename)
                                      Example: input "protein.pdb" → files named "protein_*.txt"
    
    Returns:
        tuple: (consensus_ranking, comparison_dataframe)
            - consensus_ranking (list): Final consensus ranking dicts
                                       See generate_consensus() for structure
            - comparison_dataframe (pd.DataFrame): Exported comparison table
                                                   Same data as CSV file
    
    Temporary Files:
        Creates files: _tmp_{preset_name}_*.pdb, .fasta, .sto
        These are automatically deleted after analysis completes.
    
    Output Files:
        - {output_prefix}_consensus_ranking.txt: Human-readable report
        - {output_prefix}_preset_comparison.csv: Spreadsheet format
    
    """
        
    if output_prefix is None:
        output_prefix = os.path.splitext(os.path.basename(protein_pdb))[0]
    
    logger.info(f"="*60)
    logger.info(f"MULTI-PRESET CONSENSUS ANALYSIS")
    logger.info(f"Protein: {protein_pdb}")
    logger.info(f"Presets: {presets}")
    
    analyzer = ConsensusAnalyzer()
    # Maps preset name → {pocket_id: coordinate_array}
    pocket_coords_dict = {}
    
    #  Run each preset independently 
    for preset_name in presets:
        logger.info(f"\n[{presets.index(preset_name)+1}/{len(presets)}] Running preset: {preset_name}")
        
        # Load configuration for this preset (overrides base config)
        config = load_config(base_config, preset=preset_name, verbose=False)
        
        #  Run pipeline for this preset 
        structure, _ = bio_pockets.get_protein_structure(protein_pdb)
        
        # Generate unique temporary filenames (avoid conflicts between presets)
        temp_clean = f"_tmp_{preset_name}_cleaned.pdb"
        temp_fasta = f"_tmp_{preset_name}_query.fasta"
        temp_aln = f"_tmp_{preset_name}_alignment.sto"
        
        # Step 1: Clean structure
        bio_pockets.save_clean_protein(structure, temp_clean)
        _, clean_atoms = bio_pockets.get_protein_structure(temp_clean)
        
        # Step 2: Extract sequence for conservation analysis
        bio_pockets.extract_sequence_from_pdb(clean_atoms, temp_fasta)
        
        # Step 3: Conservation analysis (optional, depends on config)
        cons_scores = None
        if config['conservation']['enabled']:
            db_path = config['conservation']['default_database']
            if os.path.exists(db_path):
                result = bio_pockets.run_jackhmmer_alignment(temp_fasta, db_path, temp_aln, config)
                if result:
                    cons_scores = bio_pockets.calculate_conservation_scores(temp_aln, clean_atoms)
        
        # Step 4: Geometric pocket detection
        grid = bio_pockets.create_search_grid(clean_atoms, config['grid']['spacing_angstrom'])
        candidates = bio_pockets.find_pocket_points(grid, clean_atoms, config)
        clustered_pockets = bio_pockets.cluster_pocket_points(candidates, config)
        
        # Step 5: Ranking
        ranking_data = bio_pockets.rank_pockets_master_score(
            clustered_pockets,
            clean_atoms,
            cons_scores,
            config
        )
        
        # Store results
        analyzer.add_result(preset_name, ranking_data)
        pocket_coords_dict[preset_name] = clustered_pockets
        
        logger.info(f"  ✓ Found {len(ranking_data)} pockets")
        
        # Cleanup temporary files (save disk space)
        for temp_file in [temp_clean, temp_fasta, temp_aln]:
            if os.path.exists(temp_file):
                os.remove(temp_file)
    
    #  Generate Consensus 
    logger.info(f"\n[{len(presets)+1}/{len(presets)+1}] Generating consensus ranking...")
    consensus = analyzer.generate_consensus(pocket_coords_dict)
    
    # Print summary to console
    analyzer.print_summary()
    
    #  Save output files 
    analyzer.save_consensus_report(f"{output_prefix}_consensus_ranking.txt")
    comparison_df = analyzer.save_comparison_table(f"{output_prefix}_preset_comparison.csv")
    
    logger.info(f"\nOutput files:")
    logger.info(f"  - {output_prefix}_consensus_ranking.txt")
    logger.info(f"  - {output_prefix}_preset_comparison.csv")
    
    return consensus, comparison_df

